# 🚀**Spaceship Titanic : 가상 차원 전송 승객 예측 모델 만들기**

**목차**
1. [소개](#introduce_section)
2. [데이터셋 가져오기](#dataset_section)
3. [탐색적 데이터 분석(EDA)](#eda_section)

In [1]:
# 라이브러리 import
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

<a id="introduce_section"></a>
# **소개**
2912년에 오신 것을 환영합니다. 당신의 데이터 과학 기술은 우주의 미스터리를 풀기 위해 꼭 필요합니다. 우리는 4광년 떨어진 곳으로부터 전송을 받았는데, 상황이 그리 좋지 않아 보입니다.

**스페이스쉽 타이타닉**은 한 달 전 발사된 성간 여객선입니다. 약 13,000명의 승객을 태운 이 배는 우리 태양계에서 인근 별 주위를 공전하는 세 개의 새로운 거주 가능 외계 행성으로 이주민들을 실어 나르는 첫 항해를 시작했습니다.

첫 번째 목적지인 뜨거운 '55 Cancri E'로 향하던 중, 알파 센타우리를 선회하던 스페이스쉽 타이타닉은 먼지 구름 속에 숨겨진 **시공간 이상 현상(Spacetime Anomaly)**과 충돌했습니다. 안타깝게도 1,000년 전의 이름과 같은 배처럼 비극적인 운명을 맞이했습니다. 비록 배 자체는 온전했지만, **승객의 거의 절반이 다른 차원으로 전송되었습니다!**

구조대원들이 잃어버린 승객들을 되찾을 수 있도록 돕기 위해, 당신은 손상된 우주선 컴퓨터 시스템에서 복구된 기록을 사용하여 **어떤 승객이 이상 현상에 의해 전송되었는지 예측**해야 합니다.

그들을 구하고 역사를 바꿔주세요!

<a id="dataset_section"></a>
# **데이터셋 가져오기**

In [13]:
# Pandas 데이터프레임으로 train 데이터셋 불러오기
train_df = pd.read_csv('C:/Users/User/Desktop/Github/sklearn-est15th-realfinal/Spaceship_Titanic/train.csv')
train_row = train_df.shape[0]
train_col = train_df.shape[1]
print(f"train 데이터셋의 크기는 {train_df.shape}입니다.")
print(f"승객은 {train_row}명, feature는 {train_col}개입니다.")

train 데이터셋의 크기는 (8693, 14)입니다.
승객은 8693명, feature는 14개입니다.

In [12]:
# Pandas 데이터프레임으로 test 데이터셋 불러오기
test_df = pd.read_csv('C:/Users/User/Desktop/Github/sklearn-est15th-realfinal/Spaceship_Titanic/test.csv')
test_row = test_df.shape[0]
test_col = test_df.shape[1]
print(f"test 데이터셋의 크기는 {test_df.shape}입니다.")
print(f"승객은 {test_row}명, feature는 {test_col}개입니다.")

test 데이터셋의 크기는 (4277, 13)입니다.
승객은 4277명, feature는 13개입니다.

In [4]:
# pd.concat()으로 train,test 데이터 하나로 합치기
all_data = pd.concat([train_df, test_df], axis=0, ignore_index=True)

In [6]:
all_data.shape

(12970, 14)

In [5]:
all_data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [7]:
all_data.tail()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
12965,9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter,NaN
12966,9269_01,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron,NaN
12967,9271_01,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore,NaN
12968,9273_01,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale,NaN
12969,9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley,NaN

In [8]:
# Target인 Transported 확인
print(f'합쳐진 데이터 크기: 행:{all_data.shape[0]}, 열:{all_data.shape[1]}')
print('전송 여부(Transported)')
print(all_data['Transported'].value_counts(dropna = False))

합쳐진 데이터 크기: 행:12970, 열:14
전송 여부(Transported)
Transported
True     4378
False    4315
NaN      4277
Name: count, dtype: int64

<a id="eda_section"></a>
# **탐색적 데이터 분석(EDA)**

In [11]:
train_df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

### 각 **feature**의 이름과 의미
- **PassengerId**: 승객 고유 ID. `gggg_pp` 형태입니다.
    
    - `gggg`: 함께 여행하는 **그룹** 번호 (주로 가족이지만 아닐 수도 있음).
        
    - `pp`: 그룹 내에서의 번호.
        
- **HomePlanet**: 승객이 출발한 행성 (보통 거주지).
    
- **CryoSleep**: 항해 동안 **냉동 수면(동면)** 상태를 선택했는지 여부(True/False). 동면 중인 승객은 객실 밖으로 나올 수 없습니다.
    
- **Cabin**: 승객이 머무는 객실 번호. `deck/num/side` 형태입니다.
    
    - `side`: `P` (좌현, Port) 또는 `S` (우현, Starboard).
        
- **Destination**: 승객이 내릴 목적지 행성.
    
- **Age**: 승객의 나이.
    
- **VIP**: 항해 중 특별 VIP 서비스를 신청했는지 여부(True/False).
    
- **RoomService, FoodCourt, ShoppingMall, Spa, VRDeck**: 우주선의 여러 편의시설에서 사용한 **금액**.
    
- **Name**: 승객의 이름과 성.
    
- **Transported**: 다른 차원으로 전송되었는지 여부. **Target**.

In [9]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [10]:
train_df.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8514.000000,8512.000000,8510.000000,8485.000000,8510.000000,8505.000000
mean,28.827930,224.687617,458.077203,173.729169,311.138778,304.854791
std,14.489021,666.717663,1611.489240,604.696458,1136.705535,1145.717189
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,47.000000,76.000000,27.000000,59.000000,46.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000